### ISSUE TITLE
Define bounding boxes for target cities

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/urbanriskmap-meta#7]
Hi @fadmastuti - please can you discuss with @anexact the extents for our target cities this year? We have talked about making sure that we capture the watershed as well as the formal city boundary. E.g. "Jakarta" should really be Jabodetabek?

Once you're happy with those, can you use QGIS/similar to get coordinates, and put them in a new page on the wiki?

**Comment by tomasholderness** [comment]
To get started I used http://geojson.io to draw rough boxes, and save to a new file in this repository.
https://github.com/urbanriskmap/urbanriskmap-meta/blob/master/target_cities_bounding_boxes.geojson

**Comment by fadmastuti** [comment]
Hi @talltom , after discussed with @anexact about Jabodetabek bounding box, we agreed to enlarge it up to 20km from the Jakarta boundaries. I tried to run the buffer analysis using QGIS for 20km and draw a box on it. Please see this following images:

![jkt_boundingbox_20km](https://cloud.githubusercontent.com/assets/2441950/19673212/f9c1790a-9aa7-11e6-9382-f24b1ce50188.png)

Also the same with Bandung:

![bandung_20km_boundingbox](https://cloud.githubusercontent.com/assets/2441950/19673025/2b869e18-9aa6-11e6-80ae-a5e3c8756845.png)

And Surabaya:

![surabaya_20km_boundingbox](https://cloud.githubusercontent.com/assets/2441950/19672980/bf31285a-9aa5-11e6-8542-1b9f8e66209a.png)

_*blue dash box is the boundingbox_
_*yellow areas refer to 20km buffer from the city boundaries_

**Comment by tomasholderness** [comment]
Looks good @fadmastuti - but grid labels on the maps are wrong? E.g. Jakarta is below equator?
Once you're happy with bounding boxes, can you put them on a new page on the Wiki and reference this issue? Thanks.

Something like

##### Jakarta Bounding Box

Top left corner: longitude, latitude
Top right corner: ....

**Comment by fadmastuti** [comment]
@talltom Thanks for the feedback Tom. Yes, you're right. all of them must be below the equator. Sorry about that.
OK. I will make a new page on wiki and referencing this issue

**Comment by fadmastuti** [comment]
please check on this [wiki page](https://github.com/urbanriskmap/urbanriskmap-meta/wiki/Bounding-Box-%237) @talltom

**Comment by tomasholderness** [comment]
Looks great @fadmastuti, going to close this issue. Thanks.

**Comment by tomasholderness** [comment]
Hi @fadmastuti, as the bounding boxes cover metropolitan areas, please can you also clarify names we should use to refer to these areas?:
1) Jabodetabek
2) Bandung?
3) Gerbangkertosusila?

**Comment by fadmastuti** [comment]
@talltom , In my opinion, we just can say:
1. Jabodetabek
2. Bandung
3. Surabaya

since people are already recognise those names even though we enlarge the bounding box for greater Bandung and Surabaya.
what do you think @prittandrani @anexact  ?

**Comment by tomasholderness** [comment]
Thanks @fadmastuti - I've used those names in the development schema: https://github.com/urbanriskmap/cognicity-schema/blob/dev/data/cognicity/instance_regions.data.sql

I'm going to close this, and @prittandrani or @anexact can reopen again if they want.
