### ISSUE TITLE
Define Swtich-Over Procedure for PetaJakarta.org -> PetaBencana.id

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/urbanriskmap-meta#9]
Document process as a Wiki page
- twitter accounts
- reports modules
- front-end

**Comment by matthewberryman** [comment]
@talltom check out https://github.com/urbanriskmap/urbanriskmap-meta/wiki/Launch-transition-procedure 
@fadmastuti @prittandrani note that steps 1 and 9 involve you.
